### ISSUE TITLE
Aktuellen Stand der Projektoberfläche ins Netz stellen

### ISSUE THREAD

**Issue by olvidalo** [cceh/ntg#1]
Wir warten zurzeit auf die Bereitstellung eines Projektservers durch das Rechenzentrum. Wenn dieser verfügbar ist, soll eine aktuelle Version der Software dort aufgespielt werden.

**Comment by MarcelloPerathoner** [comment]
Demo läuft. Datenbasis: VarGenAtt_ActPh3_Initial

http://ntg.cceh.uni-koeln.de/
