### ISSUE TITLE
2786 left aside in Coherence in Attestations Mc 2:12/40-44b

### ISSUE THREAD

**Issue by KWachtel** [cceh/ntg#100]
2786 should be assigned to its first pot. ancestor 105 but is left without connection to any other witness in the coherence graph at Mc Mc 2:12/40-44b.

**Comment by MarcelloPerathoner** [comment]
2786 is ambiguous "zw b/g_f". Variant g later falls away. Same problem as #97. See there.

**Comment by MarcelloPerathoner** [comment]
duplicate of #97
