### ISSUE TITLE
Potential Ancestors assigned incorrectly

### ISSUE THREAD

**Issue by KWachtel** [cceh/ntg#111]
In Coherence in Attestations for Mc 13:15/2-4 c, the 4th potential ancestors of 1342 (namely c:03) is shown, but two others with higher ranks are skipped (a: 892 and a: 019). The list of Relatives of 1342 shows them as second and third pot. anc. with the same percentage of agreement. In such cases the witness with the higher ranking number and higher total of shared passages should be picked, in this case a:892.

**Comment by MarcelloPerathoner** [comment]
I can see no error here. 03 is inside the default connectivity of 5, and thus trumps all other ancestors. If you lower the connectivity to 3, 1342 will be assigned to 892.

**Comment by KWachtel** [comment]
Agreed. Sorry, I overlooked that 1342 and 03 share the same variant.
