### ISSUE TITLE
error reading cited in place of the superordinate variant

### ISSUE THREAD

**Issue by KWachtel** [cceh/ntg#30]
In 13:11/38-46b (Phase 4 <http://ntg.cceh.uni-koeln.de/ph4/coherence#51311038-46>) the error reading bf1 <επεσεν αυτον αχλυς και> is cited in place of the superordinate variant b <επεσεν επ αυτον αχλυς και>. Please check whether this happened also in other passages and correct script accordingly.

**Comment by MarcelloPerathoner** [comment]
b is witnessed only by 02C, and thus gets eliminated from the apparatus. We are only left with bf1, witnessed by 02*V and with bf2 witnessed by 03. Still investigating ...

**Comment by KWachtel** [comment]
Ok. So we need a new rule here. If only a faulty form of a variant is attested, then assign the witnesses to the respective variant in ActsnnGVZ where LABEZSUF NOT LIKE %f%.

**Comment by MarcelloPerathoner** [comment]
That will probably not work because we have many variants that have only a faulty reading attested, eg:

```
select anfadr, endadr, labez, group_concat(distinct labezsuf order by labezsuf) as suf \
  from att group by anfadr, endadr, labez having suf = 'f';

+----------+----------+-------+------+
| anfadr   | endadr   | labez | suf  |
+----------+----------+-------+------+
| 50103031 | 50103031 | b     | f    |
| 50105023 | 50105023 | b     | f    |
| 50109002 | 50109010 | f     | f    |
| 50109012 | 50109020 | b     | f    |
| 50109012 | 50109020 | c     | f    |
...
585 rows
```

The alternative is to show in the apparatus what the mss. actually read. That will leave us with a few more rows but is sure to work.

**Comment by KWachtel** [comment]
You are right, that's striking. Can we print the 'f' in such cases?
