### ISSUE TITLE
Lesart a falsch dargestellt

### ISSUE THREAD

**Issue by KWachtel** [cceh/ntg#51]
Bei 1:9/2-10 wird statt der Lesart a και τουτα ειπων βλεποντων αυτων die Lesart zw dargestellt. Außerdem erscheint die Lesart zw als solche nur, wenn „Splits“ geklickt wurde.

**Comment by MarcelloPerathoner** [comment]
In der GVZ-Tabelle ist bei P74 labez = "zw" und labezsuf = "a-e" statt "a/e". Das führt dazu, daß "a" als labez promoviert wird. Nun stehen aber zwei Lesarten "a" in der Datenbank von denen einer Text zufällig ausgewählt wird.
