### ISSUE TITLE
zz... Dub in Apparatus

### ISSUE THREAD

**Issue by KWachtel** [cceh/ntg#53]
Die nicht eindeutig zuzuordnenden Zeugen sollen nicht mit „zz“ sondern mit „zw“ gekennzeichnet werden. Die infrage kommenden Varianten sollen genannt werden, aber „Dub“ ist dann überflüssig. Z.B. soll bei 15:25/10 P74 statt bei „zza/b Dub“ bei „zw_a/b“ stehen. Auch in den Diagrammen sollte P74 hier mit zw verzeichnet sein.

**Comment by MarcelloPerathoner** [comment]
In der VarGenAtt sind diese Zeugen mit "zz" gekennzeichnet. Bei aktivierten Splits wird die VarGenAtt ausgelesen (varnew + labezsuf), bei nicht aktivierten Splits wird der Apparatus ausgelesen (labez + labezsuf).
In der neuen Datenbankstruktur wird das Problem nicht mehr vorkommen, da das varnew Feld getrennt wird.
