### ISSUE TITLE
Connectivity und Splits

### ISSUE THREAD

**Issue by KWachtel** [cceh/ntg#62]
Wenn eine Bezeugung gesplittet wird, bezieht sich der gewählte Conn-Wert auf die Splits, als handelte es sich um unterschiedliche Varianten.
Bsp: 4:25/2-24. Wenn ich hier in „Coh. in Attestations“ Conn=All wähle, wird für 1718 nicht der nächste potenzielle Vorfahr innerhalb der a-Bezeugung angezeigt (das wäre 323 als 34. Vorfahr) sondern 2805, der 49. Vorfahr innerhalb des Splits a2. Da es bei Abfragen mit Conn=All darum geht, den nächsten pot. Vorfahren innerhalb der gesamten Bezeugung einer Variante zu bestimmen, muss auch der gewählte Conn-Wert auf die gesamte Bezeugung (ohne Beachtung von Splits) angewandt werden.

**Comment by MarcelloPerathoner** [comment]
Fixed: reason "splits" param in server was reverted.
