### ISSUE TITLE
Falscher Text bei Variante a

### ISSUE THREAD

**Issue by KWachtel** [cceh/ntg#64]
Bei 2:20/6 und 2:26/38-40 stimmt der Text bei a nicht. Er muss mit dem Text der Leitzeile übereinstimmen.

**Comment by KWachtel** [comment]
Es scheint einen Zusammenhang mit Issue 63 zu geben, das schon geschlossen wurde. Der falsche a-Text erschien zunächst bei vorangestelltem „null“.

**Comment by MarcelloPerathoner** [comment]
Die Auswahl der Lesart richtet sich nach der Häufigkeit. Bisher wurde bei der Auswahl der Lesart nicht berücksichtigt ob es such um eine 'f'- oder 'o'-Lesart handelte.

Im originalen Apparat ist die richtige Lesart die häufigste:
```
acts_ph4=# select hs, labez, labezsuf, lesart from original_att 
where begadr = 50220006 and labez = 'a' order by lesart;
  hs   | labez | labezsuf |     lesart      
-------+-------+----------+-----------------
 1704* | a     | f2       | μεταστραφησε
 A     | a     |          | μεταστραφησεται
 05C1  | a     |          | μεταστραφησεται
 1704C | a     |          | μεταστραφησεται
 05C3  | a     | f1       | μεταστραφησται
```
Nach Wegfall der Korrekturhände ergibt sich jedoch nur noch:
```
acts_ph4=# select hs, labez, labezsuf, lesart from att 
where begadr = 50220006 and labez = 'a' and certainty = 1.0 order by lesart;
  hs  | labez | labezsuf |     lesart      
------+-------+----------+-----------------
 1704 | a     | f2       | μεταστραφησε
 A    | a     |          | μεταστραφησεται
```
Es wurde fälschlicherweise die alphabetisch niedrigere Lesart ausgewählt. Dies wurde nun behoben in dem nicht-'fo'-Lesarten jetzt Vorrang erhalten.

Es bleibt aber das grundsätzliche Problem bestehen, daß ~600 Lesarten ausschließlich durch 'fo'-Varianten bezeugt sind. (Dieses Problem betrifft nur den Apparatus, nicht die errechneten Kohärenzwerte.) z.B. bei:
```
acts_ph4=# select begadr, endadr, hs, labez, labezsuf, lesart from original_att 
where begadr = 50103031;
  begadr  |  endadr  | hs  | labez | labezsuf |   lesart   
----------+----------+-----+-------+----------+------------
 50103031 | 50103031 | A   | a     |          | om
 50103031 | 50103031 | 181 | b     | f        | φαινομενος
```

**Comment by KWachtel** [comment]
Mit dem Vorrang der nicht-fo-Lesarten ist das Problem gelöst, denn wenn eine solche nicht vorliegt, heißt das, dass die Variante ausschließlich fehlerhaft überliefert ist und dass die Herausgeber keine korrekte Form rekonstruieren können. Es wäre schön, wenn in einem solchen Fall auch das f aus labezsuf ausgegeben würde, also im Beispiel 1:3/31 bf.
