### ISSUE TITLE
Coherence Diagrams for Mc 1:14/16-18

### ISSUE THREAD

**Issue by KWachtel** [cceh/ntg#77]
Bei Mc 1:14/16-18 werden Coherence at Variant Passages und Coherence in Attestations für Variante b nicht angezeigt.

**Comment by MarcelloPerathoner** [comment]
Also happens in Mc 2:21/12-16

**Comment by MarcelloPerathoner** [comment]
Mc 2:21/12-16 b  has a priority cycle 105 -> 2786 -> 2517 -> 105

![screenshot_2018-12-12_19-05-58](https://user-images.githubusercontent.com/7013063/49889487-ee59ec00-fe41-11e8-8134-10c47f2806ea.png)

**Comment by MarcelloPerathoner** [comment]
Same cycle in Mc 1:14/16-18 b.
