### ISSUE TITLE
ambiguous witness

### ISSUE THREAD

**Issue by KWachtel** [cceh/ntg#97]
At Mc 3:27/2-8 witness 04? appears under a, but not under b. In our apparatus the note is zw a/b, so 04? should also appear under b. Consequently Coherence in Attestations shows 04 as a witness not linked to its ancestor A or, if A is excluded, 01.

**Comment by KWachtel** [comment]
I just noticed that variant b is attested only by 04C2 and therefore has not been imported. In such cases the respective witness (here 04*) should be kept out of the apparatus.

**Comment by MarcelloPerathoner** [comment]
variant b is attested only by "04 zw a/b". if variant b is to fall out of the apparatus (as it did -- but we could decree it should not) then we need another step during import to reassign 04 from "zw a/b" to "a".
